config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  get     'register'                =>  'users#new',        as: 'new_register'
  get     'users/new'               =>  'users#new'
  post    'register'                =>  'users#create',     as: 'register'
  post    'users'                   =>  'usrs#create'
  get     'users/:id'               =>  'users#show',       as: 'user'
  get     'login'                   =>  'sessions#new',     as: 'new_login'
  get     'sessions/new'            =>  'sessions#new'
  post    'login'                   =>  'sessions#create',  as: 'login'
  post    'sessions'                =>  'sessions#create'
  delete  'logout'                  =>  'sessions#destroy',  as: 'logout'
  delete  'sessions'                =>  'sessions#destroy'

  resources :songs

end

app/models/add.rb
class Add < ActiveRecord::Base
  belongs_to :user
  belongs_to :song
end

app/models/song.rb
class Song < ActiveRecord::Base
    belongs_to :user
    has_many :adds, dependent: :destroy
    has_many :users_added, through: :adds, source: :user

    validates :title, :artist, presence: true, length: 2..25
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :songs
  has_many :adds, dependent: :destroy
  has_many :songs_adds, through: :adds, source: :song
  before_save :downcase

  validates :first_name, :last_name, presence: true
  validates :email, uniqueness: {case_sensitive: false }, presence: true, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i}

  def downcase
    self.first_name.downcase!
    self.last_name.downcase!
    self.email.downcase!
  end

end

app/controllers/adds_controller.rb
class AddsController < ApplicationController
    def show
      @user = User.find(params[:id])
      @song = User.find(params[:id]).songs_added
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by_email(params[:user][:email])
        if user
          if user.try(:authenticate, params[:user][:password])
              session[:user_id] = user.id

              return redirect_to user_path user.id
          end
            flash[:errors] = ['Password is incorrect']
        else
            flash[:errors] = ['Invalid account. Register first.']
        end
        return redirect_to :back
    end

    def destroy
        session.delete(:user_id) if session[:user_id]
        return redirect_to new_login_path
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    def create
      song = Song.new(song_params)
      song.user = User.find(session[:user_id])
      song.count = 0

      if song.save
        redirect_to :back
      else
        flash[:errors] = song.errors.full_messages
            redirect_to :back
      end
    end

    def show
      @title = Song.find(params[:id])
      @song = Song.find(params[:id]).user_added
    end

    def update
      song = Song.find(params[:id])
      number = song.count +1 
      song.update(count: number)
      Add.create(user: User.find(session[:user_id]),song: Song.find(params[:id]))
      redirect_to user_path
    end

    private
      def song_params
          params.require(:song).permit(:title, :artist)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
    end

    def create
        user = User.create(user_params)

        if user.valid?
            session[:user_id] = user.id
            # puts 'error'
            return redirect_to user_path user.id 
        end
        flash[:errors] = user.errors.full_messages
        # puts 'contin'
        return redirect_to :back
    end

    def show
        @user = User.find(params[:id])
        @song = Song.all
    end

    private
        def user_params
            params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
        end
end

app/helpers/adds_helper.rb
module AddsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/adds/adds.html.erb
<a href="users_path<%= session[:user_id] %>">Dashboard</a>
<h1><%= @user.first_name %> <%= @user.last_name %>'s Playlist</h1>

<table>
    <tr>
        <th>Song</th>
        <th>Artist</th>
        <th>Count</th>
    </tr>

    <% @song.each do |song| %>

    <tr>
        <td><a href="songs_path<%= song.id %>"><%= song.title %></a></td>
		<td><%= song.artist %></td>
		<td><%= song.count %> added</td>
	</tr>

	<% end %>
</table>

app/views/application/index.html.erb
<div class="row">
    <div class="col-1"> </div>
    <div class="col-5"> <%= render "partials/register" %></div>
    <div class="col-5"> <%= render  "partials/login" %></div>
    <div class="col-1"> </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Login</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="<%= root_path %>">Login Register</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if current_user %>
          <li class="nav-item">
            <a class="nav-link" href="<%= logout_path %>" data-method="delete">Logout</a>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_register_path %>">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_login_path %>">Login</a>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <div class="contain">
    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
          <p><%= error %></p>
      <% end %>
    <% end %>
    <%= yield %>  
  </div>
</body>
</html>

app/views/partials/_login.html.erb
<h4>Login</h4>
<form action="<%= login_path %>" method="post" class="form">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
    <div class="form-group">
        <input type="text" name="user[email]" class="form-control" id="email" placeholder="Email" />
    </div>
    <div class="form-group">
        <input type="password" name="user[password]" class="form-contol" id="password" placeholder="Password" />
    </div>
    <div class="form-group">
        <button class="btn btn-primary" type="submit">Login</button>
    </div>
</form>

app/views/partials/_register.html.erb
<h4>Register</h4>
<form action="<%= register_path %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
    <div class="form-group">
        <input type="text"  name="user[first_name]" class="form-control" id="first_name" placeholder="First Name" />
    </div>
    <div class="form-group">
        <input type="text" name="user[last_name]" class="form-control" id="last_name" placeholder="Last Name" />
    </div>
    <div class="form-group">
        <input type="text" name="user[email]" class="form-control" id="email" placeholder="Email" />
    </div>
    <div class="form-group">
        <input type="password" name="user[password]" class="form-contol" id="password" placeholder="Password" />
    </div>
    <div class="form-group">
        <input type="password" name="user[password_confirmation]" id="password_confirmation" placeholder="Password Conformation" />  
    </div>
    <div class="form-group">
        <button class="btn btn-primary" type="submit">Register</button>
    </div>
</form>

app/views/songs/show.html.erb
<a href="/users/<%= session[:user_id] %>">Dashboard</a>

<h2>Others who added <%= @song.song %> - <%= @song.artist %></h2>

<% @song.each do |song| %>
	<p><a href="songs_path<%= user.id %>"><%= user.first_name %> <%= user.last_name %></a></p>
<% end %>

app/views/users/new.html.erb
<%= render  "partials/register" %>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-9">
        <h4>Show</h4>
        <p>First Name: <%= @user.first_name %> </p>
    </div>
</div>
<h4>All the songs in our hub:</h4>
<table>
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Count</th>
        <th>Likes</th>
    </tr>
    <% @song.each do |song| %>
    <tr>
        <td><%= song.artist %></td>
        <td><a href="song<%= song.id %>"><%= song.title %></a></td>
        <td><%= song.count %></td>
        <td>
            <form action="songs_path<%= song.id %>" method="post">
                <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
                <input type="submit" value="Add">
            </form>
        </td>
    </tr>
    <% end %>

</table>

<h4>Add a song</h4>
<form action="songs_path<%= song.id %>" method="post">
	<input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
	<p><label for="song_title">Title: </label>
	<input type="text" id="song_title" name="song[title]"></p>
	<p><label for="song_artist">Artist: </label>
	<input type="text" id="song_artist" name="song[artist]"></p>
	<p><input type="submit" value="Add Title"></p>
</form>